### PR TITLE
Improved tests

### PR DESCRIPTION
**Pull request by yaroslavche**
Added `infection/infection`, `phpstan/phpstan`.
Added `FunctionsTest`
Fixed tests namespace
Updated dev-dependecies
Removed `php-documentor` as dev-dependency (need workaround or approve)

Tools:
`composer phpstan`
`composer infection`

```
Metrics:
         Mutation Score Indicator (MSI): 89%
         Mutation Code Coverage: 95%
         Covered Code MSI: 94%
```
WIP.

### CODE REVIEW

**Comment by yaroslavche** [comment]
Hi, @MarkBaker!
My proposition: to set the required version php ^7.2, since 7.1 will soon be unsupported.

**Comment by MarkBaker** [comment]
> My proposition: to set the required version php ^7.2, since 7.1 will soon be unsupported.
As you can see in travis ^7.2 works fine. I should fix nightly also.
This library is used by other libraries that do still use PHP ^5.6 for the moment, so that isn't an option till the release of PHP 7.4, when I plan to switch them to PHP ^7.1, and this library can then be adjusted accordingly.

**Comment by MarkBaker** [comment]
Just out of interest, why remove the type hints?

**Comment by yaroslavche** [comment]
> Just out of interest, why remove the type hints?

Oh, sorry, I will revert that back. I blunted something, and decided that the typhints added along with the return type =)

> This library is used by other libraries

Ah, ok, I understand. Seems it can be solved. Need just use dev dependecies which not requires 7.2

**Comment by yaroslavche** [comment]
So, seems I completed. With `composer.7.2.json` 100% code coverage =) With `composer.json` (old packages) it is almost 100%, IDK why, research is needed. I know that my vision of writing tests is also not perfect and tests can be optimized. Also, this is not a good solution with replacing the `composer.json` file in `.travis.yml` for `^7.2`. But it does work. Hope this helps and gives you some ideas for the new version =)

Screenshot_20190903_231517

**Comment by MarkBaker** [comment]
Sorry it's taken me a while to get back to you; but with a number of different changes in the one PR, I've been trying to separate them down to the individual changes while I've assessed them so that I can evaluate them one at a time.

**Comment by MarkBaker** [comment]
But thank you for your efforts, it really is appreciated. It hasn't only improved this library, but also shown me how to add infection and phpstan to some of my other libraries, a task that I had been planning but hadn't yet got round to doing.

**Pull request merged**
